setwd("~/Documents/Elections_Ontario_App/elections_ontario_app")
election_and_party <- readRDS("./data/election_and_party.rds")

df_annotation <- election_and_party %>%
  group_by(Year) %>%
  mutate(Pct.Votes = Votes.Cast/sum(Votes.Cast)*100) %>%
  mutate(Party.Temp = if_else(Pct.Votes <= 0.5, "Other", Party)) %>%
  group_by(Year, Party.Temp) %>%
  summarize(Votes.Cast = sum(Votes.Cast), Pct.Votes = sum(Pct.Votes))

Party.Acr <- c("CON", "IND", "L", NA, "CON", "CL", "IND", "L", NA, "CON", "CI", "CLR", "IND", "L", "LI", "CON", "CI", "IND", "L", "CON", "CI" ,"IND", "LAB", "L", "LI", "CON", "IND", "LAB", "L", NA, "CON", "CER", "ER", "L", "LER", NA, "---", "CON", "CIP", "CP", "CPP", "IND", "L", "LOI", "LPP", NA, "PI", "PPA", "CON", "IND", "L", NA, "CON", "IND", "L", NA, "PRH", "CON", "L", "LI", NA, "CON", "CI", "IND", "LAB", "L", NA, "S", "CON", "CI", "IND", "LAB", "L", NA, "S", "CON", "IND", "LAB", "L", "LT", NA, "S", "TEM", "CON", "CI", "IND", "LAB", "LUF", "L", "LIF", NA, "SOL", "SLB", "UF", "CON", "IND", "LAB", "L", "LI", "PRO", "UF", "CON", "CI", "LAB", "L", "LI", "LPG", "LPH", NA, "PRO", "PRI", "PRH", "UF", "CON", "CI", "LAB", "L", "LPG", NA, "PRO", "PRH", "UF", "CCF", "C", "CON", "IND", "L", "LI", "LPG", NA, "UF", "CCF", "CON", "CI", "FL", "LP", "L", "LI", "LPG", NA, "CCF", "LP", "L", "LI", NA, "PC", "CCF", "IND", "LP", "L", "LL", "LPG", NA, "PC", "CCF", "LP", "L", NA, "PC", "UOE", "CCF", "LP", "L", NA, "PC", "CCF", "IND", "LP", "L", NA, "PC", "CCF", "L", NA, "PC", "L", "ND", NA, "PC", "L", "ND", NA, "PC", "I", "L", "NDP", NA, "PC", "L", "NDP", NA, "PC", "L", "NDP", NA, "PC", "L", "ND", NA, "PC", "IND", "ND", "L", NA, "PC", "FCP", "ND", "L", NA, "PC", "COR", "FCP", "GPO", "LIB", "LTN", "NDP", NA, "PCP", "FCP", "IND", "LIB", "NDP", NA, "PCP", "FCP", "GPO", "IND", "NDP", "LIB", NA, "PCP", "FCP", "GPO", "LIB", "NDP", NA, "PCP", "FCP", "NDP", "LIB", NA, "PCP", "GPO", "GPO", "NDP", "LIB", NA, "PCP", "NDP", "LIB", "LTN", NA, "PCP", "GPO", "GPO", "NDP", "LIB", "LTN", NA, "PCP", "GPO", "IND", "NBO", "NDP", "LIB", "ONP", NA, "PCP")

Party.Col <- c("blue", "magenta", "red", NA, "blue", "black", "magenta", "red", NA, "blue", "black", "black", "magenta", "red", "black", "blue", "black", "magenta", "red", "blue", "black", "magenta", "black", "red", "black", "blue", "magenta", "black", "red", NA, "blue", "black", "black", "red", "black", NA, "black", "blue", "black", "black", "black", "magenta", "red", "black", "black", NA, "black", "black", "blue", 'magenta', "red", NA, "blue", "magenta", "red", NA, "black", "blue", "red", "black", NA, "blue", "black", "magenta", "black", "red", NA, "black", "blue", "black", "magenta", "black", "red", NA, "black", "blue", "magenta", "black", "red", "black", NA, "black", "black", "blue", "black", "magenta", "black", "black", "red", "black", NA, "black", "black", "black", "blue", "magenta", "black", "red", "black", "black", "black", "blue", "black", "black", "red", "black", "black", "black", NA, "black", "black", "black", "black", "blue", "black", "black", "red", "black", NA, "black", "black", "black", "black", "black", "blue", "magenta", "red", "black", "black", NA, "black", "orange", "blue", "black", "black", "black", "red", "black", "black", NA, "orange", "black", "red", "black", NA, "blue", "orange", "magenta", "black", "red", "black", "black", NA, "blue", "orange", "black", "red", NA, "blue", "black", "orange", "black", "red", NA, "blue", "black", "magenta", "black", "red", NA, "blue", "black", "red", NA, "blue", "red", "orange", NA, "blue", "red", "orange", NA, "blue", "magenta", "red", "orange", NA, "blue", "red", "orange", NA, "blue", "red", "orange", NA, "blue", "red", "orange", NA, "blue", "magenta", "orange", "red", NA, "blue", "black", "orange", "red", NA, "blue", "black", "black", "green", "red", "black", "orange", NA, "blue", "black", "magenta", "red", "orange", "NA", "blue", 'black', "green", "magenta", "orange", "red", NA, "blue", "black", "green", "red", "orange", NA, "blue", "black", "orange", "red", NA, "blue", "green", "green", "orange", "red", NA, "blue", "orange", "red", "black", NA, "blue", "green", "green", "orange", "red", "black", NA, "blue", "green", "magenta", "black", "orange", "red", "black", NA, "blue")

df_annotation <- df_annotation %>% add_column(Party.Acr = Party.Acr, Party.Col = Party.Col)